import { getSetting, setSetting } from "../chat/settings-manager";
import type { GitHubConfig } from "@avv/shared";

const GITHUB_API = "https://api.github.com";

// ── PAT Management ───────────────────────────────────────────

export function getGitHubConfig(): GitHubConfig | null {
  return getSetting<GitHubConfig>("github");
}

export async function connectGitHub(token: string): Promise<GitHubConfig> {
  // Validate token by fetching user info
  const res = await fetch(`${GITHUB_API}/user`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
    },
  });

  if (!res.ok) {
    throw new Error(`GitHub authentication failed: ${res.status}`);
  }

  const user = (await res.json()) as { login: string };

  const config: GitHubConfig = {
    token,
    username: user.login,
    validated: true,
  };

  setSetting("github", config);
  return config;
}

// ── Repository Operations ────────────────────────────────────

export async function createRepo(
  name: string,
  description?: string,
  isPrivate = true,
): Promise<{ fullName: string; htmlUrl: string; cloneUrl: string }> {
  const config = getGitHubConfig();
  if (!config?.token) throw new Error("GitHub not connected");

  const res = await fetch(`${GITHUB_API}/user/repos`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${config.token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      name,
      description: description ?? `Generated by AVV`,
      private: isPrivate,
      auto_init: false,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Failed to create repo: ${res.status} ${body}`);
  }

  const repo = (await res.json()) as {
    full_name: string;
    html_url: string;
    clone_url: string;
  };

  return {
    fullName: repo.full_name,
    htmlUrl: repo.html_url,
    cloneUrl: repo.clone_url,
  };
}

export async function pushFiles(
  repoFullName: string,
  files: Map<string, string>,
  commitMessage = "Initial commit from AVV",
): Promise<void> {
  const config = getGitHubConfig();
  if (!config?.token) throw new Error("GitHub not connected");

  const headers = {
    Authorization: `Bearer ${config.token}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
  };

  // Create blobs for each file
  const treeEntries: Array<{
    path: string;
    mode: string;
    type: string;
    sha: string;
  }> = [];

  for (const [path, content] of files) {
    const blobRes = await fetch(
      `${GITHUB_API}/repos/${repoFullName}/git/blobs`,
      {
        method: "POST",
        headers,
        body: JSON.stringify({
          content: Buffer.from(content).toString("base64"),
          encoding: "base64",
        }),
      },
    );

    if (!blobRes.ok) throw new Error(`Failed to create blob for ${path}`);
    const blob = (await blobRes.json()) as { sha: string };

    treeEntries.push({
      path: path.replace(/^\/+/, ""),
      mode: "100644",
      type: "blob",
      sha: blob.sha,
    });
  }

  // Create tree
  const treeRes = await fetch(
    `${GITHUB_API}/repos/${repoFullName}/git/trees`,
    {
      method: "POST",
      headers,
      body: JSON.stringify({ tree: treeEntries }),
    },
  );

  if (!treeRes.ok) throw new Error("Failed to create tree");
  const tree = (await treeRes.json()) as { sha: string };

  // Create commit
  const commitRes = await fetch(
    `${GITHUB_API}/repos/${repoFullName}/git/commits`,
    {
      method: "POST",
      headers,
      body: JSON.stringify({
        message: commitMessage,
        tree: tree.sha,
      }),
    },
  );

  if (!commitRes.ok) throw new Error("Failed to create commit");
  const commit = (await commitRes.json()) as { sha: string };

  // Update main ref
  const refRes = await fetch(
    `${GITHUB_API}/repos/${repoFullName}/git/refs`,
    {
      method: "POST",
      headers,
      body: JSON.stringify({
        ref: "refs/heads/main",
        sha: commit.sha,
      }),
    },
  );

  if (!refRes.ok) {
    // Ref might already exist, try updating
    const updateRes = await fetch(
      `${GITHUB_API}/repos/${repoFullName}/git/refs/heads/main`,
      {
        method: "PATCH",
        headers,
        body: JSON.stringify({ sha: commit.sha }),
      },
    );
    if (!updateRes.ok) throw new Error("Failed to update ref");
  }
}
